version: '3.8'

services:
  web:
    image: webdevops/php-apache:alpine-php7
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app/:/app
    networks:
      - escolar_net

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: escolar_db

    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./dumps/escolardb.sql:/docker-entrypoint-initdb/escolar_db.sql
    
    networks:
      - escolar_net

networks:
  escolar_net:
    driver: bridge    
    
  
    

